FROM eclipse-temurin:21-jdk-alpine

# Install Maven
RUN apk add --no-cache maven bash

WORKDIR /app
COPY . .

# Download dependencies offline
RUN mvn dependency:go-offline

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]
